### ISSUE TITLE
Using a backtick causes the following character to be accentuated

### ISSUE THREAD

**Issue by momesana** [larsenwork/Gidole#47]
While using the font in a web application, any combination of ` + char e. g. (`a or `x) results in a character with a grave accent. There are similar issues with a caret (i.e. ^) sign in combination with another character. The issue is very much similar to the one described here regarding the noto sans fonts (https://github.com/googlei18n/noto-fonts/issues/736, https://news.ycombinator.com/item?id=12655054). I've included the type-face as follows:

```css
@font-face {
    font-family: 'Gidole';
    src: url('../fonts/Gidole/Gidole-Regular.ttf') format('truetype');
    font-weight: normal;
    font-style: normal;
}
```

Using Noto Sans:
![screenshot from 2018-10-24 17-31-04](https://user-images.githubusercontent.com/12494/47442434-a5c37200-d7b2-11e8-9c46-10029d9f9b71.png)

Using Gidole:
![screenshot from 2018-10-24 17-30-55](https://user-images.githubusercontent.com/12494/47442436-a5c37200-d7b2-11e8-8883-015ce1dd6a40.png)

Interestingly, this issue only pertains to the *.ttf fonts available for download. The Gidole homepagemakes use of a *.woff variant of Gidole (hosted here: http://gidole.github.io/fonts/Gidole.woff) that does not suffer the same problem.
